import { createOpenRouter } from '@openrouter/ai-sdk-provider'
import { AIProvider } from './types'

export const OPENROUTER_MODELS = [
    "anthropic/claude-3-haiku",
    "anthropic/claude-3-opus",
    "anthropic/claude-3-sonnet",
    "anthropic/claude-3.5-haiku",
    "anthropic/claude-3.5-haiku-20241022",
    "anthropic/claude-3.5-sonnet",
    "anthropic/claude-3.5-sonnet-20240620",
    "anthropic/claude-3.7-sonnet",
    "anthropic/claude-opus-4",
    "anthropic/claude-opus-4.1",
    "anthropic/claude-sonnet-4",
    "fireworks/firellava-13b",
    "google/gemini-2.5-flash",
    "google/gemini-2.5-flash-lite",
    "google/gemini-2.5-pro",
    "google/gemini-flash-1.5",
    "google/gemini-flash-1.5-8b",
    "google/gemini-pro-1.5",
    "google/gemma-3-12b-it",
    "google/gemma-3-27b-it",
    "google/gemma-3-4b-it",
    "liuhaotian/llava-13b",
    "liuhaotian/llava-yi-34b",
    "meta-llama/llama-3.2-11b-vision-instruct",
    "meta-llama/llama-3.2-90b-vision-instruct",
    "meta-llama/llama-4-maverick",
    "meta-llama/llama-4-scout",
    "meta-llama/llama-guard-4-12b",
    "microsoft/phi-4-multimodal-instruct",
    "minimax/minimax-01",
    "mistralai/mistral-medium-3",
    "mistralai/mistral-medium-3.1",
    "mistralai/mistral-small-3.1-24b-instruct",
    "mistralai/mistral-small-3.2-24b-instruct",
    "mistralai/pixtral-12b",
    "mistralai/pixtral-large-2411",
    "moonshotai/kimi-vl-a3b-thinking",
    "nousresearch/nous-hermes-2-vision-7b",
    "openai/chatgpt-4o-latest",
    "openai/codex-mini",
    "openai/gpt-4-turbo",
    "openai/gpt-4.1",
    "openai/gpt-4.1-mini",
    "openai/gpt-4.1-nano",
    "openai/gpt-4o",
    "openai/gpt-4o-mini",
    "openai/gpt-5",
    "openai/gpt-5-chat",
    "openai/gpt-5-mini",
    "openai/gpt-5-nano",
    "openai/o1",
    "openai/o1-pro",
    "openai/o3",
    "openai/o3-pro",
    "openai/o4-mini",
    "openai/o4-mini-high",
    "opengvlab/internvl3-14b",
    "opengvlab/internvl3-2b",
    "perplexity/sonar",
    "perplexity/sonar-pro",
    "perplexity/sonar-reasoning-pro",
    "qwen/qwen-2.5-vl-7b-instruct",
    "qwen/qwen-vl-max",
    "qwen/qwen-vl-plus",
    "qwen/qwen2.5-vl-32b-instruct",
    "qwen/qwen2.5-vl-3b-instruct",
    "qwen/qwen2.5-vl-72b-instruct",
    "thudm/glm-4.1v-9b-thinking",
    "x-ai/grok-2-vision-1212",
    "x-ai/grok-4",
    "x-ai/grok-vision-beta",
    "z-ai/glm-4.5v"
] as const

export type OpenRouterModel = (typeof OPENROUTER_MODELS)[number]

export const DEFAULT_OPENROUTER_MODEL: OpenRouterModel = 'anthropic/claude-3.5-haiku-20241022'

const openrouterClient = createOpenRouter({
  apiKey: process.env.OPENROUTER_API_KEY || '',
})

export const openrouterProvider: AIProvider = {
  name: 'OpenRouter',
  models: OPENROUTER_MODELS,
  defaultModel: DEFAULT_OPENROUTER_MODEL,
  getModel: (modelName: string) => openrouterClient(modelName),
}